# Zmienne globalne

@FixIt.Api_HostAddress = http://localhost:5013

# Test rejestracji
POST {{FixIt.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "test@user.pl",
  "password": "Password123!",
  "firstName": "Tester",
  "lastName": "Manualny"
}

### 

# Test logowania i zapisanie tokena
POST {{FixIt.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "test@user.pl",
  "password": "Password123!"
}

###

> {% client.global.set("token", response.body.token) %}
###

# Pobieranie wszystkich ticketów
GET {{FixIt.Api_HostAddress}}/api/tickets
Authorization: Bearer {{token}}
Accept: application/json

###

# Tworzenie nowego zg³oszenia
POST {{FixIt.Api_HostAddress}}/api/tickets
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Zepsuta drukarka",
  "description": "Drukarka w biurze nr 5 nie chce drukowaæ na czarno."
}

###

# Przyjmowanie zg³oszenia (Claim)
POST {{FixIt.Api_HostAddress}}/api/tickets/38c5b462-9708-4faa-89af-977716a5a14d/claim
Authorization: Bearer {{token}}